### ISSUE TITLE
Navigation on https://prosperityhomeowner.com/team/support-and-training/

### ISSUE THREAD

**Issue by shannonbaldwin** [shannonbaldwin/onehomeowner.com#2]
@codextiny 
Is there any workaround we can do to where the default lands on a different section so that the tiles align with the subject? Right now, it defaults at "get started" and displays all of the tiles. Could we add an "All" tab so that the default made more sense?

![image](https://github.com/shannonbaldwin/onehomeowner.com/assets/167017886/f4d8833a-40d1-424c-aa90-b2abc7773e6c)

**Comment by shannonbaldwin** [comment]
@codextiny
I am getting an error when I click to edit the tiles in the portfolio. 
![image](https://github.com/shannonbaldwin/onehomeowner.com/assets/167017886/eec6d27e-2533-4e9e-b540-d1ed359b1969)

[ https://prosperityhomeowner.com/team/support-and-training/](url)

**Comment by codextiny** [comment]
@shannonbaldwin 

We have enabled "All" tab on tiles, please check.

also when we edit tiles its working fine for us, please see screenshot, it might be some connection problem from your side.

![image](https://github.com/shannonbaldwin/onehomeowner.com/assets/113863175/31724ec9-be78-43e8-9d75-3ce18fc40efd)

**Comment by shannonbaldwin** [comment]
@codextiny

https://github.com/shannonbaldwin/onehomeowner.com/assets/167017886/7798e6b6-00f3-41f9-b4bc-0fd69394088d

Those images that pop-up are not part of the post at all. You can see the others take me to the error page.

**Comment by shannonbaldwin** [comment]
@codextiny


https://github.com/shannonbaldwin/onehomeowner.com/assets/167017886/cf7c4b5f-e1d0-4de6-8ec1-bbbeab840269

**Comment by codextiny** [comment]
@shannonbaldwin 

![image](https://github.com/shannonbaldwin/onehomeowner.com/assets/113863175/f574086b-9d92-48e0-a563-d36f82a081f6)

There might be some issue, video is not working for us ..

**Comment by shannonbaldwin** [comment]
@codextiny My internet was down. Here are the videos again.

https://github.com/shannonbaldwin/onehomeowner.com/assets/167017886/46b06aa1-689e-47c9-8dbb-913e61feeff2


https://github.com/shannonbaldwin/onehomeowner.com/assets/167017886/b0b56053-11c4-4a56-8465-dea270b65de8

**Comment by codextiny** [comment]
@shannonbaldwin 

Did you add/install any new plugin recently ??
How long have these pages been down?

**Comment by shannonbaldwin** [comment]
@codextiny No.

**Comment by shannonbaldwin** [comment]
We did copy this site from everythinghome.ai

**Comment by codextiny** [comment]
@shannonbaldwin 

After spending hours, the issue is fixed.
![image](https://github.com/shannonbaldwin/onehomeowner.com/assets/113863175/90c2bc1a-db00-468b-aec7-d7bf6e80dc68)

As a draft, it was working fine.
https://prosperityhomeowner.com/team/?post_type=portfolio&p=1537&preview=true
https://prosperityhomeowner.com/team/wp-admin/post.php?post=1537&action=elementor

if it does not work for you please clear the cache of your browser and check

**Comment by codextiny** [comment]
@shannonbaldwin 

Please do not mention outsourcing and do work outside of Fiverr because they can freeze our accounts.
![image](https://github.com/shannonbaldwin/onehomeowner.com/assets/113863175/1475c8b6-791c-43eb-9136-f65ce6f71103)
even if we write email in the Fiverr chat box they show a warning

Here is our Slack info
URL: codextiny.slack.com
Email: codextiny@gmail.com
